#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MODELS_CONF="${ROOT_DIR}/config/models.conf"
ENV_FILE="${ROOT_DIR}/.env"
DETECTED_ENV_FILE="${ROOT_DIR}/.env.detected"
PID_FILE="${LLM_PID_FILE:-/tmp/llm_server.pid}"

load_env_files() {
  if [[ -f "${ENV_FILE}" ]]; then
    set -a
    # shellcheck source=/dev/null
    source "${ENV_FILE}"
    set +a
  fi

  if [[ -f "${DETECTED_ENV_FILE}" ]]; then
    set -a
    # shellcheck source=/dev/null
    source "${DETECTED_ENV_FILE}"
    set +a
  fi
}

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

resolve_model() {
  local alias="${1:?model alias is required}"

  if [[ ! -f "${MODELS_CONF}" ]]; then
    echo "Missing model registry: ${MODELS_CONF}" >&2
    return 1
  fi

  local row
  row="$(awk -F'|' -v alias="${alias}" 'NF == 4 && $1 == alias { print; exit }' "${MODELS_CONF}")"
  if [[ -z "${row}" ]]; then
    echo "Unknown model alias '${alias}'. Available aliases:" >&2
    awk -F'|' 'NF == 4 && $1 !~ /^#/ { printf "  %s (%s, %s)\n", $1, $3, $4 }' "${MODELS_CONF}" >&2
    return 1
  fi

  IFS='|' read -r MODEL_ALIAS MODEL_REF MODEL_BACKEND MODEL_QUANT <<<"${row}"
  export MODEL_ALIAS MODEL_REF MODEL_BACKEND MODEL_QUANT
}

write_detected_env() {
  local backend="${1:?backend is required}"
  local profile="${2:?profile is required}"
  local gpu_count="${3:-0}"
  local max_vram_mb="${4:-0}"
  local default_port="${5:-11434}"

  cat >"${DETECTED_ENV_FILE}" <<EOF
# Generated by scripts/setup_env.sh. Safe to delete and regenerate.
DETECTED_BACKEND=${backend}
HARDWARE_PROFILE=${profile}
GPU_COUNT=${gpu_count}
MAX_VRAM_MB=${max_vram_mb}
DEFAULT_PORT=${default_port}
EOF
}
